### ISSUE TITLE
Incosistent naming

### ISSUE THREAD

**Issue by sPawelRietz** [123pik1/ADAproject#8]
There's an issue of incosistent naming in the code. ex.
task type Producer is
      entry Start(Ingredient: in Ingredient_Type; Cooking_Time: in Integer);
   end Producer;
It's bad practice to use Cooking_Time instead of Production_Time as expected (same for ingredient)

There are 2 solutions:
*We either rename all of the variables so that they match (time consuming) ex.
task type Cook is
      entry Start(Ingredient: in Ingredient_Type; Cooking_Time: in Integer);
   end Cook;

*Or we stick with the abstract names and only use specific names in string outputs:
task type Producer is
      entry Start(Product: in Product_Type; Production_Time: in Integer);
   end Product;

Please share your opinion (mine is second option)

**Comment by 123pik1** [comment]
second option is ok
